routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	$lots = \App\Lots::all();
    return view('lots.index', compact('lots'));
});

Route::get('/contacts', function() {
  return view('contacts', compact('contacts'));
});

Route::resource('/lots', 'LotController');


Route::get('/home', 'HomeController@index');

Auth::routes();

app/Lots.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lots extends Model
{
    protected $fillable = [
    	'location',
    	'price',
    	'image',
    	'description'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LotController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LotController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lots = \App\Lots::all();
        return view('lots.index', compact('lots'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('lots.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $lots = \App\Lots::create($request->all());
        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lot = \App\Lots::find($id);
        return view('lots.create', compact('lot'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \App\Lots::find($id)->update($request->all());
        return redirect()->route('lots.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Lots::find($id)->delete();
        return redirect()->route('lots.index');
    }
}

resources/views/contacts.blade.php
@extends('welcome')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="container marketing">
				<div class="row featurette">
                	<div class="col-md-7">
						<h2><strong>This is how you can contact us:</strong></h2>
						<h3><span class="text-muted">Contact our administrator via email:</span> admin@admin.lt <span class="text-muted"> or telephone:</span> +370 (630) 00000</h3>
						</br>
						<h3><strong>You can also visit our main office!</strong></h3>
						<h3>Working hours: Monday to Friday 9:00 - 17:00</p></h3>
					</div>
				</div>
			</div>
			<div class="responsive-iframe"> 
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2306.7341207400427!2d25.265054216039804!3d54.67910798174803!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dd9472c09e8bb1%3A0x8d2b9e6b4a1aa84f!2s%C5%A0vitrigailos+g.+8%2C+Vilnius+03223!5e0!3m2!1sen!2slt!4v1481477688894" width="1170" height="750" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>
	</div>
	<hr class="featurette-divider">
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/footer.blade.php
    <footer>
    <div id="footer-container" class="container">
        <div id="footer-row" class="row">
            <a href="{{ url('/login') }}" class="pull-right btn btn-default">Login</a>
            @if (Auth::user()) 
            <a href="{{ url('/logout') }}" class="pull-right btn btn-default" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
            @endif
            <p>&copy; 2016 EasyLand, Inc. All rights reserved. &middot;</p>
        </div>
    </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    {{-- <script src="../../dist/js/bootstrap.min.js"></script> --}}
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    {{-- <script src="../../assets/js/vendor/holder.min.js"></script> --}}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    {{-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> --}}

</body>
</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Buy land lot online! Easy lots, cheap, fast, no fraud, guaranteed legal trade. Immovable property on mobile, pictures, accurate descriptions, real estates!">
    <meta name="author" content="Julius Lauciunas">
    {{-- <link rel="icon" href="../../favicon.ico"> --}}
    <title>EasyLand | Buy a land lot online!</title>
    <!-- Styles -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <!-- Latest compiled CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
  </head>
<!-- NAVBAR
================================================== -->
  <body>
        <div class="navbar-wrapper">
          <div class="container">

            <nav class="navbar navbar-inverse navbar-static-top">
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{{ url('lots') }}"><strong>EasyLand.eu</strong> - our best lots for you online!</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav pull-right">
                    <li><a href="{{ url('lots') }}">Choose your lot!</a></li>
                    <li><a href="{{ url('contacts') }}">Contacts</a></li>
                  </ul>
                </div>
              </div>
            </nav>

          </div>
        </div>


        <!-- Carousel
        ================================================== -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img class="first-slide" src="{{ asset('img/carousel-bg.jpg') }}" alt="First slide">
              <div class="container">
                <div class="carousel-caption">
                  <h1>Easy and cheap way to buy your new property!</h1>
                  <p>Browse through our current land lots below!</p>
                </div>
              </div>
            </div>
            <div class="item">
              <img class="second-slide" src="{{ asset('img/carousel-bg.jpg') }}" alt="Second slide">
              <div class="container">
                <div class="carousel-caption">
                  <h1>Just choose your favorite land lot!</h1>
                  <p>It's just THAT simple! Choose your new property and contact us. We will take care of everything else.</p>
                </div>
              </div>
            </div>
            <div class="item">
              <img class="third-slide" src="{{ asset('img/carousel-bg.jpg') }}" alt="Third slide">
              <div class="container">
                <div class="carousel-caption">
                  <h1>Browse on your PC, Tablet or mobile!</h1>
                  <p>Our website is optimized for hassle-free browsing throughout all platforms!</p>
                </div>
              </div>
            </div>
          </div>
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

resources/views/lots/create.blade.php
@extends('welcome')
@section('content')
<div class="container">
    <div class="row">
	@if (Auth::user())   
	    @if(isset($lot))
	    <form class="form-group" action="{{ route('lots.update', $lot->id) }}" method="POST">
	    <input type="hidden" name="_method" value="PUT">
	    @else
	    <form class="form-group" action="{{ route('lots.store') }}" method="POST">
	    @endif
	        {{ csrf_field() }}
	        <fieldset>
	            <label for="location">Location:</label>
	            @if(isset($lot))
	            <input value="{{ $lot->location }}" class="form-control" type="text" name="location">
	            @else
	            <input class="form-control" type="text" name="location">
	            @endif
	            
	            <label for="price">Price:</label>
	            @if(isset($lot))
	            <input value="{{ $lot->price }}" class="form-control" type="text" name="price">
	            @else
	            <input class="form-control" type="text" name="price">
	            @endif

	            <label for="image">Image:</label>
	            @if(isset($lot))
	            <input value="{{ $lot->image }}" class="form-control" type="text" name="image">
	            @else
	            <input class="form-control" type="text" name="image">
	            @endif

	            <label for="description">Description:</label>
	            @if(isset($lot))
	            <input value="{{ $lot->description }}" class="form-control" type="text" name="description">
	            @else
	            <input class="form-control" type="text" name="description">
	            @endif
	            <button class="btn btn-success" type="submit" name="submit">{{ isset($lot) ? 'Edit' : 'Add'}}</button>
	        </fieldset>
	    </form>
	    
	    @if(isset($lot))
	    <form class="form-group" action="{{ route('lots.destroy', $lot->id) }}" method="POST">
	    {{ csrf_field() }}
	    <input type="hidden" name="_method" value="DELETE">
	        <button class="btn btn-danger">Delete</button>
	    </form>
	    @endif
	    </div>
	@else
	<h2>You're accessing the content made for admin only!</h2>
	<p>Please log in or try hacking somewhere else.</p>
	@endif
    <hr class="featurette-divider">

</div>
@endsection

resources/views/lots/index.blade.php
@extends('welcome')
@section('content')
		<div class="col-md-12">
			 <div class="container marketing">
            @foreach($lots as $lot)
              <div class="row featurette">
                <div class="col-md-7">
                  <h2 class="featurette-heading"> {{ $lot->location }} </br> <span class="text-muted"> {{ $lot->price }} &#8364; </span></h2>
                  <p class="lead"> {{ $lot->description }} m&sup2; </br> <small><span class="text-muted">Lot posted at: {{ $lot->created_at }} </span></small></p>
                </div>
                <div class="col-md-5">
                  <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image" src="{{ $lot->image }}">
                </div>
              </div>
              <a href="{{ url('contacts') }}" class="btn btn-success">Buy now!</a>
              @if (Auth::user())
                <a href="{{ route('lots.create') }}" class="btn btn-default">Create</a>
                <a href="{{ route('lots.edit', $lot->id) }}" class="btn btn-default">Edit</a>
              @endif
              <hr class="featurette-divider">
            @endforeach
        </div>
		</div>
@endsection